pipeline {
    agent any  
    // {
    //     docker {
    //         image 'node:6-alpine'
    //         args '-p 3000:3000'
    //     }
    // }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                // bat 'npm install'
                echo 'finish build update'
            }
        }
        stage('Test') {
            steps {
                  echo 'finish test update'
            }
        }
    }
}
